USE [SayHenTai]
GO

/****** Object:  Table [dbo].[CHI_TIET_TRUYEN]    Script Date: 5/30/2023 7:07:06 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHI_TIET_TRUYEN](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[ID_CHUONG_MUC] [numeric](18, 0) NOT NULL,
	[ID_TRUYEN] [numeric](18, 0) NOT NULL,
	[IMAGE_URL] [nvarchar](max) NULL,
	[WIDTH] [nvarchar](50) NULL,
	[HEIGHT] [nvarchar](50) NULL,
	[ALT] [nvarchar](350) NULL,
	[ID_SOURCE] [nvarchar](50) NULL,
 CONSTRAINT [PK_CHI_TIET_TRUYEN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


GO

/****** Object:  Table [dbo].[CHUONG_MUC]    Script Date: 5/30/2023 7:07:13 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHUONG_MUC](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[ID_TRUYEN] [decimal](18, 0) NOT NULL,
	[TEN] [nvarchar](250) NULL,
	[SO_LAN_DOC] [int] NULL,
	[THOI_GIAN_CAP_NHAT] [nvarchar](250) NULL,
	[URL] [nvarchar](max) NULL,
 CONSTRAINT [PK_CHUONG_MUC] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


GO

/****** Object:  Table [dbo].[TRUYEN]    Script Date: 5/30/2023 7:07:20 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TRUYEN](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[TEN] [nvarchar](250) NOT NULL,
	[TAC_GIA] [nvarchar](250) NULL,
	[SO_LAN_DOC] [int] NULL,
	[TRANG_THAI] [nvarchar](50) NULL,
	[THE_LOAI] [nvarchar](50) NULL,
	[RATING] [nvarchar](50) NULL,
	[IMAGE_COVER] [nvarchar](max) NULL,
 CONSTRAINT [PK_TRUYEN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO